version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: tomuki_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-tomuki}
      POSTGRES_USER: ${POSTGRES_USER:-tomuki}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tomuki}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
